// <auto-generated />
namespace HR.Migrations.HrMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class holiday_Yearadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(holiday_Yearadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201805101519130_holiday_Yearadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
